# Generated by Django 5.0 on 2025-12-05 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='contests/banners/', verbose_name='バナー画像')),
                ('start_at', models.DateTimeField(verbose_name='開始日時')),
                ('end_at', models.DateTimeField(verbose_name='終了日時')),
                ('voting_end_at', models.DateTimeField(blank=True, null=True, verbose_name='投票終了日時')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開')),
                ('max_entries_per_user', models.IntegerField(default=1, verbose_name='ユーザーあたり最大応募数')),
                ('max_images_per_entry', models.IntegerField(default=5, verbose_name='エントリーあたり最大画像数')),
                ('twitter_hashtag', models.CharField(blank=True, help_text='例: フォトコンテスト (# は不要)', max_length=100, verbose_name='Twitterハッシュタグ')),
                ('twitter_auto_fetch', models.BooleanField(default=False, verbose_name='Twitter自動取得')),
                ('twitter_auto_approve', models.BooleanField(default=False, verbose_name='Twitter投稿の自動承認')),
                ('twitter_last_fetch', models.DateTimeField(blank=True, null=True, verbose_name='最終取得日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'コンテスト',
                'verbose_name_plural': 'コンテスト',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切り', max_length=500, verbose_name='タグ')),
                ('source', models.CharField(choices=[('manual', '手動投稿'), ('twitter', 'Twitter自動取得')], default='manual', max_length=20, verbose_name='投稿元')),
                ('twitter_tweet_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ツイートID')),
                ('twitter_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='TwitterユーザーID')),
                ('twitter_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitterユーザー名')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='ツイートURL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('flagged', models.BooleanField(default=False, verbose_name='フラグ')),
                ('flag_reason', models.TextField(blank=True, verbose_name='フラグ理由')),
                ('view_count', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contest.contest', verbose_name='コンテスト')),
            ],
            options={
                'verbose_name': 'エントリー',
                'verbose_name_plural': 'エントリー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entries/%Y/%m/%d/', verbose_name='画像')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='entries/thumbs/%Y/%m/%d/', verbose_name='サムネイル')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='幅')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高さ')),
                ('is_thumbnail_ready', models.BooleanField(default=False, verbose_name='サムネイル生成済み')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contest.entry', verbose_name='エントリー')),
            ],
            options={
                'verbose_name': 'エントリー画像',
                'verbose_name_plural': 'エントリー画像',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='理由')),
                ('resolved', models.BooleanField(default=False, verbose_name='解決済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='contest.entry', verbose_name='エントリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
            ],
            options={
                'verbose_name': '通報',
                'verbose_name_plural': '通報',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='0-100', verbose_name='スコア')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contest.entry', verbose_name='エントリー')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to=settings.AUTH_USER_MODEL, verbose_name='審査員')),
            ],
            options={
                'verbose_name': '審査員スコア',
                'verbose_name_plural': '審査員スコア',
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contest.entry', verbose_name='エントリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'ordering': ['-created_at'],
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
