# Generated by Django 5.0 on 2025-12-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_auto_approve_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='require_twitter_account',
            field=models.BooleanField(default=False, help_text='有効にすると、投稿にはTwitterアカウント連携が必須になります', verbose_name='Twitter連携必須'),
        ),
    ]
