# Generated by Django 5.0 on 2025-12-09 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contest_require_twitter_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='この評価項目の点数', max_digits=5, verbose_name='点数')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '詳細スコア',
                'verbose_name_plural': '詳細スコア',
                'ordering': ['criteria__order'],
            },
        ),
        migrations.CreateModel(
            name='EntryCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'エントリー部門紐付け',
                'verbose_name_plural': 'エントリー部門紐付け',
                'ordering': ['category__order'],
            },
        ),
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 構図、色彩、独創性', max_length=100, verbose_name='評価項目名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('max_score', models.IntegerField(default=10, help_text='この項目の最大点数', verbose_name='最大点数')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '審査基準',
                'verbose_name_plural': '審査基準',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='judgescore',
            options={'ordering': ['-total_score', '-created_at'], 'verbose_name': '審査員スコア', 'verbose_name_plural': '審査員スコア'},
        ),
        migrations.AddField(
            model_name='contest',
            name='judging_type',
            field=models.CharField(choices=[('vote', '投票方式'), ('score', '点数方式')], default='vote', help_text='投票方式または点数方式を選択', max_length=20, verbose_name='審査方式'),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_votes_per_judge',
            field=models.IntegerField(default=3, help_text='投票方式の場合のみ有効。各審査員が投票できる作品数', verbose_name='審査員あたり最大投票数'),
        ),
        migrations.AddField(
            model_name='judgescore',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='各評価項目の合計点', max_digits=6, verbose_name='総合点'),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='comment',
            field=models.TextField(blank=True, verbose_name='総評コメント'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 風景部門、人物部門、グランプリ', max_length=100, verbose_name='部門名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('max_votes_per_judge', models.IntegerField(blank=True, help_text='この部門での審査員の最大投票数。未設定の場合はコンテストの設定を使用', null=True, verbose_name='審査員あたり最大投票数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contest.contest', verbose_name='コンテスト')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='judgescore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='judgescore',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contest.category', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='vote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='contest.category', verbose_name='部門'),
        ),
        migrations.AlterUniqueTogether(
            name='judgescore',
            unique_together={('entry', 'judge', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('entry', 'user', 'category')},
        ),
        migrations.AddIndex(
            model_name='judgescore',
            index=models.Index(fields=['category', 'judge'], name='contest_jud_categor_f29f98_idx'),
        ),
        migrations.AddIndex(
            model_name='judgescore',
            index=models.Index(fields=['entry', 'category'], name='contest_jud_entry_i_d8654d_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['category', 'user'], name='contest_vot_categor_d77e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['entry', 'category'], name='contest_vot_entry_i_3283d0_idx'),
        ),
        migrations.AddField(
            model_name='detailedscore',
            name='judge_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_scores', to='contest.judgescore', verbose_name='審査員スコア'),
        ),
        migrations.AddField(
            model_name='entrycategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_assignments', to='contest.category', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='entrycategoryassignment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='contest.entry', verbose_name='エントリー'),
        ),
        migrations.AddField(
            model_name='judgingcriteria',
            name='category',
            field=models.ForeignKey(blank=True, help_text='部門固有の基準。未設定の場合は全部門共通', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judging_criteria', to='contest.category', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='judgingcriteria',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_criteria', to='contest.contest', verbose_name='コンテスト'),
        ),
        migrations.AddField(
            model_name='detailedscore',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_scores', to='contest.judgingcriteria', verbose_name='審査基準'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('contest', 'name')},
        ),
        migrations.RemoveField(
            model_name='judgescore',
            name='score',
        ),
        migrations.AlterUniqueTogether(
            name='entrycategoryassignment',
            unique_together={('entry', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='detailedscore',
            unique_together={('judge_score', 'criteria')},
        ),
    ]
