# Generated by Django 5.0 on 2025-12-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0007_detailedscore_entrycategoryassignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "賞",
                "verbose_name_plural": "賞",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="max_votes_per_judge",
            field=models.IntegerField(
                blank=True,
                help_text="この賞での審査員の最大投票数。未設定の場合はコンテストの設定を使用",
                null=True,
                verbose_name="審査員あたり最大投票数",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="例: グランプリ、風景賞、人物賞、技術賞", max_length=100, verbose_name="賞名"
            ),
        ),
        migrations.DeleteModel(
            name="EntryCategoryAssignment",
        ),
    ]
