# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0008_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="enable_stages",
            field=models.BooleanField(
                default=False,
                help_text="一次審査、二次審査など段階的に審査を行う",
                verbose_name="段階審査を有効化",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="stage_count",
            field=models.IntegerField(
                default=1, help_text="審査の段階数（1以上）", verbose_name="段階数"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="stage_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='各段階の設定。例: {"1": {"name": "一次審査", "max_votes": 5}, "2": {"name": "最終審査", "max_votes": 3}}',
                verbose_name="段階別設定",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="current_stage",
            field=models.IntegerField(
                default=1, help_text="現在進行中の審査段階", verbose_name="現在の段階"
            ),
        ),
    ]
