# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0009_category_enable_stages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgescore",
            name="stage",
            field=models.IntegerField(
                default=1,
                help_text="段階審査の段階番号（1以上）",
                verbose_name="審査段階",
            ),
        ),
    ]
