# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0010_judgescore_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="stage",
            field=models.IntegerField(
                default=1,
                help_text="段階審査の段階番号（1以上）",
                verbose_name="審査段階",
            ),
        ),
        # unique_togetherを更新
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("entry", "user", "category", "stage")},
        ),
    ]
