# Generated by Django 5.0 on 2026-04-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0011_vote_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="judgescore",
            unique_together={("entry", "judge", "category", "stage")},
        ),
        migrations.CreateModel(
            name="EntryView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewed_at", models.DateTimeField(auto_now_add=True, verbose_name="閲覧日時")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="contest.entry",
                        verbose_name="エントリー",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審査員",
                    ),
                ),
            ],
            options={
                "verbose_name": "エントリー閲覧記録",
                "verbose_name_plural": "エントリー閲覧記録",
                "ordering": ["-viewed_at"],
                "unique_together": {("entry", "judge")},
            },
        ),
    ]
